### ISSUE TITLE
Mejorar sistema de roles

### ISSUE THREAD

**Issue by fernandoparada18** [Transcarabobo/control_operaciones_recaudacion#3]
Se debe mejorar el sistema de autorizacion de accesos para el ingreso de los usuarios a los diferentes modulos del sistema ya que en la medida que se vayan incorporando mas modulos a la aplicacion se van a tener crear mas middleware para permitir y/o denegar a los usuarios el uso del modulo. Por lo que propongo el uso del paquete Shinobi para reestructuras el sistema de roles de usuario.

**Comment by fernandoparada18** [comment]
@Pedropin te encargo las vistas de los CRUD de permisos y roles.

**Comment by Pedropin** [comment]
Terminado Parte de Vista para los Roles.con el uso del paquete "Shinobi"

**Comment by fernandoparada18** [comment]
@Pedropin las vistas tienen un bug que no le da acceso a los usuarios aun teniendo el permiso correcto. Utiliza el metodo `@if(Auth::user()->can('slug-permiso'))` en las vistas para corregir el error.
